version: '2'
services:
  mysql:
    image: mariadb:10.1.21
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: openidctest
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    command:
      # https://issues.jboss.org/browse/KEYCLOAK-3873
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    volumes:
      - ../mysql-init:/docker-entrypoint-initdb.d
  keycloak:
    image: jboss/keycloak-mysql:2.5.5.Final
    links:
      - mysql
    environment:
      #KEYCLOAK_USER: admin
      #KEYCLOAK_PASSWORD: openidctest
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      # Workaround for container using legacy Docker links, resulting in
      # "WFLYCTL0211: Cannot resolve expression 'jdbc:mysql://${env.MYSQL_PORT_3306_TCP_ADDR}:${env.MYSQL_PORT_3306_TCP_PORT}
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: "3306"
    expose:
      - "8080"
      - "9090"
    # For local browser; you also need "keycloak" in your hosts file
    ports:
      - "8080:8080"
      - "9990:9990"
    # Uncomment the following and docker-compose up keycloak again to export realms
    volumes:
      - ./keycloak-setup/export:/export
    #entrypoint:
    #  - /opt/jboss/keycloak/bin/standalone.sh
    #  - -Dkeycloak.migration.action=export
    #  - -Dkeycloak.migration.provider=dir
    #  - -Dkeycloak.migration.dir=/export
  httpd-openidc:
    build: ../httpd-openidc
    image: localhost:5000/reposoft/httpd-openidc
    entrypoint:
      - echo
      - "This was just a build job. Exiting."
  openidc:
    build: ./openidc
    depends_on:
      - httpd-openidc
      - keycloak
    # Don't allow direct communication with keycloak; depends on hosting scenario
    #links:
    #  - keycloak
    expose:
      - "80"
    # For local browser; you also need "openidc" in your hosts file
    ports:
      - "80:80"
    volumes:
      - ./html-ajax:/usr/local/apache2/htdocs
  keycloak-setup:
    build: ./keycloak-setup
    links:
      - keycloak
    volumes:
      - ./keycloak-setup/export:/export
  testclient:
    build: ./client-node-request
    links:
      - openidc
      - keycloak
